# - name: Create a directory if it does not exist
#   file:
#     path: /var/tmp/ca/
#     state: directory
#     mode: '0755'

# - name: Copy ca os local to docker contrainer
#   shell: "docker cp /root/ca/{{ ca_name }} awx_task:/var/tmp/ca/{{ ca_name }}"
#   delegate_to: awx

- name: Check CA
  shell: "openssl req -noout -text -in /root/ca/{{ ca_name }} | grep 'Signature Algorithm' | awk '{print $3}'" 
  register: sha

- name: If Sha1
  debug:
    msg: Pending
  when: "sha1WithRSAEncryption" == sha.stdout

- name: If Sha2
  debug:
    msg: Issues Certificate on Microsoft CA (2012)
  when: "sha256WithRSAEncryption" == sha.stdout